version: "3"

services:
  music-bot:
    build: .
    image: discord-musicbot:latest
    container_name: music-bot
    restart: unless-stopped
    networks:
      - lavalink-net
    depends_on:
      - lavalink
    volumes:
      - ./botconfig.js:/usr/src/app/botconfig.js:ro

  lavalink:
    image: fredboat/lavalink:dev
    container_name: music-lavalink
    hostname: lavalink
    restart: unless-stopped
    networks:
      - lavalink-net
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml:ro
    # ports:
    #   - 2333:2333

networks:
  lavalink-net:
